version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_URL=sqlite://db.sqlite3
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
